# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  # Coverage thresholds (must match Jest config)
  status:
    project:
      default:
        target: 80%
        threshold: 2%  # Allow 2% drop without failing
    patch:
      default:
        target: 75%  # New code should have at least 75% coverage

  # Precision of coverage percentage
  precision: 2
  round: down

# PR Comment settings
comment:
  layout: "header, diff, flags, files, footer"
  behavior: default  # Update existing comment
  require_changes: true  # Only comment if coverage changed
  require_base: false
  require_head: true

# File/path configuration
ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "__tests__/**/*"
  - "coverage/**/*"
  - "node_modules/**/*"
  - "*.config.js"
  - "*.config.ts"
  - "scripts/**/*"

# GitHub integration
github_checks:
  annotations: true

# Flag management
flags:
  unittests:
    paths:
      - lib/
      - app/
      - models/
    carryforward: true

# Notification settings (optional)
notify:
  after_n_builds: 1
  wait_for_ci: true
