packages:
  - '.'

allowBuilds:
  '@clerk/shared': true
  '@sentry/cli': true
  mongodb-memory-server: true
  msw: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@sentry/cli'
  - mongodb-memory-server
  - msw
  - sharp
  - unrs-resolver
